version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: ./gradlew clean build
      - persist_to_workspace:
          root: .
          paths:
            - build

  dockerize:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run: |
          docker build -t coffit23/spring-static-nginx ./nginx
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push coffit23/spring-static-nginx

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - dockerize:
          requires:
            - build
