version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: ./gradlew clean build
      - run: |
          mkdir -p nginx/static
          cp -r build/resources/main/static/* nginx/static/
      - persist_to_workspace:
          root: .
          paths:
            - nginx

  dockerize:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run: |
          docker build -t yourdockerhubid/spring-static-nginx ./nginx
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push yourdockerhubid/spring-static-nginx

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - dockerize:
          requires:
            - build
